name: glvnd-core22
base: core22
summary: Default implementation of graphics-core22, delegating out to multiple drivers
description: |
  A content snap containing the mesa libraries and drivers for core 22
compression: lzo
version: "0.01"

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x
  - build-on: riscv64

package-repositories:
  - type: apt
    url: http://archive.ubuntu.com/ubuntu/
    suites: [jammy]
    components: [main, universe]
    architectures: [i386]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com

parts:
  wrapper:
    plugin: dump
    source: scripts

  apis:
    # This provides the essential APIs
    #   o libEGL.so.1
    #   o libvulkan.so.1
    #   o libGLX.so.0
    #
    plugin: nil
    stage-packages:
      - libegl1
      - libgles2
      - libvulkan1
      - libglx0
    prime:
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri       # libglx0 pulls dri in
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libdrm_*  # and drm, as a result
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libEGL_*  # libegl1 pulls libegl-mesa0 in
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libGLX_*  # libglx0 pulls libglx-mesa0 in
      - usr/lib

  drm:
    # DRM userspace
    #   o libdrm.so.2
    plugin: nil
    stage-packages:
      - libdrm2
    prime:
      - usr/lib

  x11:
    # X11 support (not much cost to having this)
    plugin: nil
    stage-packages:
      - libx11-xcb1
      - libxau6
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-present0
      - libxcb-randr0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb1
      - libxdamage1
      - libxdmcp6
      - libxshmfence1
    prime:
      - usr/lib
      - usr/share/X11

  wayland:
    # Wayland support (not much cost to having this)
    plugin: nil
    stage-packages:
      - libwayland-client0
      - libwayland-egl1
      - libwayland-server0
    prime:
      - usr/lib

  apis-i386:
      # This provides the essential APIs
      #   o libEGL.so.1
      #   o libvulkan.so.1
      #   o libGLX.so.0
      #
      plugin: nil
      stage-packages:
        - on amd64:
          - libegl1:i386
          - libgles2:i386
          - libvulkan1:i386
          - libglx0:i386
      override-prime: |
        if [ ${CRAFT_TARGET_ARCH} = "amd64" ]; then craftctl default; fi
      prime:
        - -usr/lib/i386-linux-gnu/dri       # libglx0 pulls dri in
        - -usr/lib/i386-linux-gnu/libdrm_*  # and drm, as a result
        - -usr/lib/i386-linux-gnu/libEGL_*  # libegl1 pulls libegl-mesa0 in
        - -usr/lib/i386-linux-gnu/libGLX_*  # libglx0 pulls libglx-mesa0 in
        - usr/lib

  drm-i386:
    # DRM userspace
    #   o libdrm.so.2
    plugin: nil
    stage-packages:
      - on amd64:
        - libdrm2:i386
    override-prime: |
      if [ ${CRAFT_TARGET_ARCH} = "amd64" ]; then craftctl default; fi
    prime:
      - usr/lib

  x11-i386:
    # X11 support (not much cost to having this)
    plugin: nil
    stage-packages:
      - on amd64:
        - libx11-xcb1:i386
        - libxau6:i386
        - libxcb-dri2-0:i386
        - libxcb-dri3-0:i386
        - libxcb-present0:i386
        - libxcb-randr0:i386
        - libxcb-sync1:i386
        - libxcb-xfixes0:i386
        - libxcb1:i386
        - libxdamage1:i386
        - libxdmcp6:i386
        - libxshmfence1:i386
    override-prime: |
      if [ ${CRAFT_TARGET_ARCH} = "amd64" ]; then craftctl default; fi
    prime:
      - usr/lib
      - usr/share/X11

  wayland-i386:
    # Wayland support (not much cost to having this)
    plugin: nil
    stage-packages:
      - on amd64:
        - libwayland-client0:i386
        - libwayland-egl1:i386
        - libwayland-server0:i386
    override-prime: |
      if [ ${CRAFT_TARGET_ARCH} = "amd64" ]; then craftctl default; fi
    prime:
      - usr/lib

slots:
  graphics-core22:
    interface: content
    source:
      read:
        - $SNAP/etc
        - $SNAP/usr
        - $SNAP_DATA/drivers

plugs:
  glvnd-driver-core22:
    interface: content
    content: glvnd-driver-core22
    target: $SNAP/glvnd-sources
